version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: protheus_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: maltflow_api
    restart: always
    ports:
      - '${API_PORT}:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_DATABASE=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy