version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: protheus_mysql
    restart: always
    environment:
      MYSQL_DATABASE: protheus_mock
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'